---
# Displayed on 'Choose language' page
language: "English"

# Displayed on the bottom of PDF pages
website: "www.csfieldguide.org.nz/en/"

structure:
    - chapters:
        numbered: yes
        listed: yes
        table_of_contents_sidebar: yes
        source_files:
            - file: chapters/introduction.md
              authors:
                - Tim Bell
                - Jack Morgan
            - file: chapters/algorithms.md
              authors:
                - Caitlin Duncan
                - Tim Bell
            - file: chapters/programming-languages.md
              authors:
                - Heidi Newton
                - Tim Bell
            - file: chapters/human-computer-interaction.md
              authors:
                - Tim Bell
                - Heidi Newton
            - file: chapters/data-representation.md
              authors:
                - Heidi Newton
                - Tim Bell
            - file: chapters/coding-introduction.md
              authors:
                - Heidi Newton
                - Tim Bell
            - file: chapters/coding-compression.md
              authors:
                - Tim Bell
                - Heidi Newton
            - file: chapters/coding-encryption.md
              authors:
                - Heidi Newton
                - Tim Bell
            - file: chapters/coding-error-control.md
              authors:
                - Heidi Newton
            - file: chapters/artificial-intelligence.md
              authors:
                - Heidi Newton
            - file: chapters/complexity-tractability.md
              authors:
                - Heidi Newton
                - Tim Bell
            - file: chapters/computer-graphics.md
              authors:
                - Rhem Munro
            - file: chapters/computer-vision.md
              authors:
                - David Thompson
                - Hayden Jackson
            - file: chapters/formal-languages.md
              authors:
                - Tim Bell
            - file: chapters/network-communication-protocols.md
              authors:
                - Sam Jarman
            - file: chapters/software-engineering.md
              authors:
                - Janina Voigt
    - curriculum-guides:
        numbered: no
        listed: yes
        table_of_contents_sidebar: yes
        source_files:
            - file: curriculum-guides/ncea/assessment-guide-level-1-introduction.md
            - file: curriculum-guides/ncea/assessment-guide-level-1-searching-algorithms.md
            - file: curriculum-guides/ncea/assessment-guide-level-1-sorting-algorithms.md
            - file: curriculum-guides/ncea/assessment-guide-level-1-human-computer-interaction.md
            - file: curriculum-guides/ncea/assessment-guide-level-1-programming-languages.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-introduction.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-achieved-representing-data.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-achieved-compression-run-length-encoding.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-achieved-error-control-check-sums.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-achieved-error-control-parity.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-achieved-encryption-caesar-cipher.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-achieved-human-computer-interaction.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-full-human-computer-interaction.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-excellence-data-representation-text.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-excellence-data-representation-numbers.md
            - file: curriculum-guides/ncea/assessment-guide-level-2-excellence-data-representation-colour.md
            - file: curriculum-guides/ncea/assessment-guide-level-3-software-engineering-methodologies.md
            - file: curriculum-guides/ncea/assessment-guide-level-3-complexity-tractability-TSP.md
            - file: curriculum-guides/ncea/assessment-guide-level-3-formal-languages-FSA-RE.md
            - file: curriculum-guides/apcsp/guide-algorithms-introduction.md
            - file: curriculum-guides/apcsp/guide-abstraction-introduction.md
            - file: curriculum-guides/apcsp/guide-creativity-introduction.md
            - file: curriculum-guides/apcsp/guide-data-and-information-introduction.md
            - file: curriculum-guides/apcsp/guide-global-impact-introduction.md
            - file: curriculum-guides/apcsp/guide-programming-introduction.md
            - file: curriculum-guides/apcsp/guide-the-internet-introduction.md
    - further-information:
        numbered: no
        listed: yes
        table_of_contents_sidebar: no
        source_files:
            - file: further-information/glossary.md
            - file: further-information/contributors.md
            - file: further-information/interactives.md
            - file: further-information/releases.md
            - file: further-information/included-files.md
    - static-pages:
        numbered: no
        listed: no
        table_of_contents_sidebar: no
        source_files:
            - file: index.md
            - file: about.md
            - file: search.md
            - file: 404.md
            - file: sitemap.md
            - file: chapters/index.md
            - file: curriculum-guides/index.md
            - file: curriculum-guides/ncea/index.md
            - file: curriculum-guides/apcsp/index.md
            - file: further-information/index.md
text_values:
    project_title: "Computer Science Field Guide"
    project_title_abbreviation: "CSFG"
    project_subtitle: "An online interactive resource for high school students learning about computer science"
    teacher_version_text: "Teacher Version"
    print_edition_text: "Print Edition"
    table_of_contents: "Table of Contents"
    authors: "Authors"
    menu_navigation: "Navigation"
    menu_item_about: "About"
    menu_item_feedback: "Give us feedback"
    menu_item_search: "Search"
    menu_item_contribute: "Contribute on GitHub"
    menu_item_language: "Change language"
    footer_sponsors_heading: "Sponsors"
    footer_sponsors_text: "Funding for this guide has been generously provided by these sponsors"
    footer_useful_links_heading: "Useful Links"
    footer_useful_links_about: "About"
    footer_useful_links_sitemap: "Sitemap"
    footer_useful_links_twitter: "Twitter"
    footer_useful_links_github: "GitHub"
    footer_contributor_text: "Produced by the <a href='http://www.cosc.canterbury.ac.nz/research/RG/CSE/'>CS Education Research Group</a>, <a href='http://www.canterbury.ac.nz/'>University of Canterbury</a>, New Zealand, and <a href='%s'>by many others</a>."
    footer_license_text: "The Computer Science Field Guide uses a <a rel='license' href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (CC BY-NC-SA 4.0) license</a>."
    homepage_chapters: "Chapters"
    homepage_curriculum_guides: "Curriculum Guides"
    homepage_further_information: "Further Information"
    homepage_download_pdf: "Download PDF"
    homepage_link_to_teachers_guide: "A teacher's guide is available, read the <a href='./about.html'>About section</a> for more details to access this."
    homepage_paragraph: "This guide features interactive activities within some of the chapters. These should work with any modern browser updated in the last year, but we are continually expanding the compatibility of these. This guide is open source and <a href='https://github.com/uccser/cs-field-guide'>available on GitHub</a>."
    feedback_heading: "Want to give us feedback?"
    feedback_paragraph_1: "Because this textbook is online itâ€™s easy for us to update it. Please use this form for any form of feedback, from tiny obvious suggestions to broad observations. We love getting positive feedback too (and it helps us to get support for this work)."
    feedback_button: "Submit Feedback"
    feedback_subheading: "Do you have a GitHub account?"
    feedback_paragraph_2: "You can directly <a href='https://github.com/uccser/cs-field-guide/issues/new'>create an issue on our GitHub repository here</a>."
    pre-release-text: "Please be aware this is a pre-release version, contents may change before release."
    print_link_to_online_resource_video: "Watch the video online at"
    print_link_to_online_resource_link: "View the link online at"
    print_link_to_online_resource_image: "View the image online at"
    print_link_to_online_resource_interactive: "Use the interactive online at"
    teacher_link_to_student_text: "Click here to view this page on the student version"
    glossary_see_also_prefix: "See also"
...
